### ISSUE TITLE
Feature: keep chat history when the conversation has been closed by the other party

### ISSUE THREAD

**Issue by vith** [Versalkul/WarframeMarketClient#1]
I'm not really sure how these chats work on the website itself but in WarframeMarketClient, I noticed that a chat I had responded to was missing when I looked for it a few minutes later.

I think the only somewhat tricky thing UI-wise would be ensuring that you can't reopen the conversation while keeping the old history visible, as it would give the impression that the other user could also still read that history which may not be the case.

**Comment by Versalkul** [comment]
As of now it is like on the website, when someone closes a chat it disapears.
But i can add a setting so that old chats dont get removed, when the other person closes the chat.

**Comment by Versalkul** [comment]
Implemented
